// main
export const TEST_MAIN_INCREMENT = 'TEST_MAIN_INCREMENT' ;

// peroson
export const TEST_PERSON_ADD_PERSON = 'TEST_PERSON_ADD_PERSON';
export const TEST_PERSON_REMOVE_PERSON = 'TEST_PERSON_REMOVE_PERSON';
export const TEST_PERSON_ADD_GUEST = 'TEST_PERSON_ADD_GUEST';
export const TEST_PERSON_REMOVE_GUEST = 'REMOVE_GUEST';
export const TEST_PERSON_TOGGLE_ATTENDING = 'TEST_PERSON_TOGGLE_ATTENDING';
// person filter
export const TEST_PERSON_SHOW_ATTENDING = 'TEST_PERSON_SHOW_ATTENDING';
export const TEST_PERSON_SHOW_ALL = 'TEST_PERSON_SHOW_ALL';
export const TEST_PERSON_SHOW_WITH_GUESTS = 'TEST_PERSON_SHOW_WITH_GUESTS';
// person reset
export const TEST_PERSON_RESET_STATE = 'TEST_PERSON_RESET_STATE';
