// main
export const TEST_MAIN_INCREMENT = 'TEST_MAIN_INCREMENT' ;

// peroson
export const TEST_PEASON_ADD_PERSON = 'TEST_PEASON_ADD_PERSON';
export const TEST_PEASON_REMOVE_PERSON = 'TEST_PEASON_REMOVE_PERSON';
export const TEST_PEASON_ADD_GUEST = 'TEST_PEASON_ADD_GUEST';
export const TEST_PEASON_REMOVE_GUEST = 'REMOVE_GUEST';
export const TEST_PEASON_TOGGLE_ATTENDING = 'TEST_PEASON_TOGGLE_ATTENDING';
// person filter
export const TEST_PEASON_SHOW_ATTENDING = 'TEST_PEASON_SHOW_ATTENDING';
export const TEST_PEASON_SHOW_ALL = 'TEST_PEASON_SHOW_ALL';
export const TEST_PEASON_SHOW_WITH_GUESTS = 'TEST_PEASON_SHOW_WITH_GUESTS';
