// main
export const TEST_MAIN_INCREMENT = 'TEST_MAIN_INCREMENT' ;

// peroson
export const TEST_PERSONS_ADD_PERSON = 'TEST_PERSONS_ADD_PERSON';
export const TEST_PERSONS_REMOVE_PERSON = 'TEST_PERSONS_REMOVE_PERSON';
export const TEST_PERSONS_ADD_GUEST = 'TEST_PERSONS_ADD_GUEST';
export const TEST_PERSONS_REMOVE_GUEST = 'REMOVE_GUEST';
export const TEST_PERSONS_TOGGLE_ATTENDING = 'TEST_PERSONS_TOGGLE_ATTENDING';
// person filter
export const TEST_PERSONS_SHOW_ATTENDING = 'TEST_PERSONS_SHOW_ATTENDING';
export const TEST_PERSONS_SHOW_ALL = 'TEST_PERSONS_SHOW_ALL';
export const TEST_PERSONS_SHOW_WITH_GUESTS = 'TEST_PERSONS_SHOW_WITH_GUESTS';
// person reset
export const TEST_PERSONS_RESET_STATE = 'TEST_PERSONS_RESET_STATE';

// person post

export const TEST_PERSONS_ADD_PERSON_GET = 'TEST_PERSONS_ADD_PERSON_GET';
export const TEST_PERSONS_ADD_PERSON_POST = 'TEST_PERSONS_ADD_PERSON_POST';
